// <auto-generated />
using System;
using Insure__Insurance_Company_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insure__Insurance_Company_.Migrations
{
    [DbContext(typeof(InsuredatabaseContext))]
    [Migration("20260131070709_UpdateLoanTable_RemoveExtraColumns")]
    partial class UpdateLoanTable_RemoveExtraColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Insure__Insurance_Company_.Models.InsuranceType", b =>
                {
                    b.Property<int>("InsuranceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("insurance_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceTypeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("insurance_name");

                    b.HasKey("InsuranceTypeId")
                        .HasName("PK__Insuranc__19DDD89BB1D5E9A1");

                    b.ToTable("InsuranceTypes");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("interest_rate");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("loan_amount");

                    b.Property<DateOnly?>("LoanDate")
                        .HasColumnType("date")
                        .HasColumnName("loan_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("user_policy_id");

                    b.HasKey("LoanId")
                        .HasName("PK__Loans__A1F79554AE68C4CC");

                    b.HasIndex("UserPolicyId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.NewsletterSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewsletterSubscriptions");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_mode");

                    b.Property<int>("PaymentMonth")
                        .HasColumnType("int");

                    b.Property<int>("PaymentYear")
                        .HasColumnType("int");

                    b.Property<int>("UserPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("user_policy_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__ED1FC9EA825DA7EC");

                    b.HasIndex("UserPolicyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal?>("CoverageAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("coverage_amount");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("insurance_type_id");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("policy_name");

                    b.Property<decimal?>("PremiumAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("premium_amount");

                    b.Property<int?>("TermYears")
                        .HasColumnType("int")
                        .HasColumnName("term_years");

                    b.HasKey("PolicyId")
                        .HasName("PK__Policies__47DA3F0302335A19");

                    b.HasIndex("InsuranceTypeId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("USER")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FDCA9CD82");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "FullName" }, "UQ_Users_Full_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ_Users_Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.UserPolicy", b =>
                {
                    b.Property<int>("UserPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPolicyId"));

                    b.Property<int?>("AgeAtPurchase")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("FinalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PaymentsLeft")
                        .HasColumnType("int");

                    b.Property<int>("PaymentsPaid")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserPolicyId")
                        .HasName("PK__UserPoli__7002C3A9EC4A5430");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPolicies");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Loan", b =>
                {
                    b.HasOne("Insure__Insurance_Company_.Models.UserPolicy", "UserPolicy")
                        .WithMany("Loans")
                        .HasForeignKey("UserPolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_Loans_UserPolicies");

                    b.Navigation("UserPolicy");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Payment", b =>
                {
                    b.HasOne("Insure__Insurance_Company_.Models.UserPolicy", "UserPolicy")
                        .WithMany("Payments")
                        .HasForeignKey("UserPolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_UserPolicies");

                    b.Navigation("UserPolicy");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Policy", b =>
                {
                    b.HasOne("Insure__Insurance_Company_.Models.InsuranceType", "InsuranceType")
                        .WithMany("Policies")
                        .HasForeignKey("InsuranceTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Policies_InsuranceTypes");

                    b.Navigation("InsuranceType");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.UserPolicy", b =>
                {
                    b.HasOne("Insure__Insurance_Company_.Models.Policy", "Policy")
                        .WithMany("UserPolicies")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPolicies_Policies");

                    b.HasOne("Insure__Insurance_Company_.Models.User", "User")
                        .WithMany("UserPolicies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserPolicies_Users");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.InsuranceType", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.Policy", b =>
                {
                    b.Navigation("UserPolicies");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.User", b =>
                {
                    b.Navigation("UserPolicies");
                });

            modelBuilder.Entity("Insure__Insurance_Company_.Models.UserPolicy", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
